### ISSUE TITLE
manage.py test is broken

### ISSUE THREAD

**Issue by zboralski** [tallstreet/jaikuenginepatch#2]
Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    execute_manager(settings)
  File "/Users/Shared/tank/pub/devel/gae/jaikuenginepatch/aepcommon/zip-packages/django-1.1.zip/django/core/management/**init**.py", line 370, in execute_manager

  File "/Users/Shared/tank/pub/devel/gae/jaikuenginepatch/aepcommon/zip-packages/django-1.1.zip/django/core/management/**init**.py", line 315, in execute

  File "/Users/Shared/tank/pub/devel/gae/jaikuenginepatch/aepcommon/zip-packages/django-1.1.zip/django/core/management/base.py", line 197, in run_from_argv
  File "/Users/Shared/tank/pub/devel/gae/jaikuenginepatch/aepcommon/zip-packages/django-1.1.zip/django/core/management/base.py", line 180, in create_parser
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/optparse.py", line 1200, in **init**
    add_help=add_help_option)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/optparse.py", line 1242, in _populate_option_list
    self.add_options(option_list)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/optparse.py", line 1025, in add_options
    self.add_option(option)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/optparse.py", line 1006, in add_option
    self._check_conflict(option)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/optparse.py", line 981, in _check_conflict
    option)
optparse.OptionConflictError: option --verbosity: conflicting option string(s): --verbosity
wolf jaikuenginepatch $

**Comment by tallstreet** [comment]
appengine requires python2.5 to run
